//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int Id { get; set; }
        public byte pizzaSize { get; set; }
        public byte crustType { get; set; }
        public byte sausage { get; set; }
        public byte peperoni { get; set; }
        public byte onions { get; set; }
        public byte peppers { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string town { get; set; }
        public string postcode { get; set; }
        public string phone { get; set; }
        public string extra { get; set; }
        public decimal cost { get; set; }
        public string name { get; set; }
    }
}
